/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.10 and the Filter Design Toolbox 4.7.
 *
 * Generated on: 01-Nov-2011 17:22:51
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 49
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s24,23 -> [-1 1)
 * Filter Internals  : Specify Precision
 *   Output          : s32,31 -> [-1 1)
 *   Product         : s39,38 -> [-1 1)
 *   Accumulator     : s43,38 -> [-16 16)
 *   Round Mode      : convergent
 *   Overflow Mode   : wrap
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2010a\extern\include\tmwtypes.h 
 */
#define __FIR_TAPS 49
int16 __FIR_NUM[49] = {
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      2,      9,     34,    110,    313,    786,   1762,   3550,
     6462,  10669,  16023,  21937,  27426,  31344,  32767,  31344,  27426,
    21937,  16023,  10669,   6462,   3550,   1762,    786,    313,    110,
       34,      9,      2,      0,      0,      0,      0,      0,      0,
        0,      0,      0,      0
};

#define __FIR_COEFS_DIV 32768

#define FIR_FILTER_DEF(NAME)  int32 __fir_input_buff[FIR_TAPS]; \
fir_object NAME = { \
__FIR_TAPS,         \
__FIR_NUM,          \
__FIR_COEFS_DIV,    \
__fir_input_buff,   \
0                   \
};                  


